// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEMCZei0qWZiIfJmYTnwURECelKyqvq_k',
    appId: '1:664383070214:web:168dcbf03fef8e763da387',
    messagingSenderId: '664383070214',
    projectId: 'tccv2-4f4e0',
    authDomain: 'tccv2-4f4e0.firebaseapp.com',
    storageBucket: 'tccv2-4f4e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpeqwvtCK3V4m0TOorhTuMYfWbD4sXV6k',
    appId: '1:664383070214:android:64fb2afe205b5a4c3da387',
    messagingSenderId: '664383070214',
    projectId: 'tccv2-4f4e0',
    storageBucket: 'tccv2-4f4e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzXppqzmRU1-TyXCiwl25VJ0vEgEhzAM',
    appId: '1:664383070214:ios:0df53f8b3b1dde893da387',
    messagingSenderId: '664383070214',
    projectId: 'tccv2-4f4e0',
    storageBucket: 'tccv2-4f4e0.firebasestorage.app',
    iosBundleId: 'com.example.tccV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKzXppqzmRU1-TyXCiwl25VJ0vEgEhzAM',
    appId: '1:664383070214:ios:0df53f8b3b1dde893da387',
    messagingSenderId: '664383070214',
    projectId: 'tccv2-4f4e0',
    storageBucket: 'tccv2-4f4e0.firebasestorage.app',
    iosBundleId: 'com.example.tccV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEMCZei0qWZiIfJmYTnwURECelKyqvq_k',
    appId: '1:664383070214:web:37de48fe396dd16b3da387',
    messagingSenderId: '664383070214',
    projectId: 'tccv2-4f4e0',
    authDomain: 'tccv2-4f4e0.firebaseapp.com',
    storageBucket: 'tccv2-4f4e0.firebasestorage.app',
  );
}
